services:
  frontend:
    container_name: simple-ciphers-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_BASE: http://localhost:5003
      VITE_PORT: 5173
    env_file:
      - ./frontend/.env

  backend:
    container_name: simple-ciphers-backend
    build:
      context: ./backend
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://hammyla:andrei8888@postgres-db:5432/simpleciphers"
      PORT: 5003
      CLIENT_URL: http://localhost:5173
      JWT_SECRET: c87274d4832e8f5bd97ff853a4595a17
    env_file:
      - ./backend/.env
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hammyla
      POSTGRES_PASSWORD: andrei8888
      POSTGRES_DB: simpleciphers
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_modules: