services:
  frontend:
    container_name: simple-ciphers-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      API_BASE: http://backend:5003
      PORT: 5173

  backend:
    container_name: simple-ciphers-backend
    build:
      context: ./backend
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://hammyla:andrei8888@postgres-db:5432/simpleciphersd
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hammyla
      POSTGRES_PASSWORD: andrei8888
      POSTGRES_DB: simpleciphers
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    

volumes:
  postgres-data: 