services:
  frontend:
    container_name: simple-ciphers-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
      - VITE_PORT=${VITE_PORT}
      - VITE_AUTH0_SECRET=${AUTH0_SECRET}
      - VITE_AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - VITE_AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - VITE_AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - CHOKIDAR_USEPOLLING=true 
    env_file:
      - ./.env

  backend:
    container_name: simple-ciphers-backend
    build:
      context: ./backend
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    command: /bin/sh -c "npx prisma migrate dev && npm run dev"

  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_modules: