services:
  backend:
    container_name: simple-ciphers-backend
    build:
      context: ./backend
    ports:
      - "5003:5003"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    buildCommand: npm install --production=false
    startCommand: npm run build
    preDeployCommand: npx prisma migrate deploy

  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_modules:
