#### GET a user's information
GET http://localhost:5003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Imdvb2dsZS1vYXV0aDJ8MTE1ODI0MjU3NDcwOTg4NTU1NDcyIiwidGltZXN0YW1wIjoxNzQxNjQwOTUwODI3LCJpYXQiOjE3NDE2NDA5NTAsImV4cCI6MTc0MTY2MjU1MH0.9BQANC_Is9HG8J-npaRAbbQyftYzGZrlhzL1yQ1id8A