#### GET a user's information
GET http://localhost:5003/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNvb2xraWRiaWxseSIsInRpbWVzdGFtcCI6MTc0MTU3NjI0OTkxNSwiaWF0IjoxNzQxNTc2MjQ5LCJleHAiOjE3NDE1OTc4NDl9.-MxNZrMVwSVnNnzVgYWRCBJIPwOjnOmARCtQoaWe1yY